// <auto-generated />
namespace PlataformaRPHD.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requestWithContactAndOrigin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requestWithContactAndOrigin));
        
        string IMigrationMetadata.Id
        {
            get { return "201707092032470_requestWithContactAndOrigin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
